#!/bin/bash

# Store the initial git status
initial_status=$(git status --porcelain)

# Run the lint command
yarn run lint --fix

# Store the status after running lint
post_lint_status=$(git status --porcelain)

# Compare the initial and post-lint statuses
if [ "$initial_status" != "$post_lint_status" ]; then
  echo "===================================="
  echo "Linters gonna lint!"
  echo "Linting made changes. Please commit these changes before pushing or push with --no-verify flag to omit this check."
  echo "===================================="
  exit 1
fi

# All goooood in safe's land!
exit 0